---
title: GTFOBins

exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md', '/CONTRIBUTING.md']

permalink: pretty

collections:
  gtfobins:
    output: true

defaults:
  - scope:
      path: '_gtfobins'
    values:
      layout: bin
